[package]
name = "psx-usb"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
defmt = "0.3.5"
defmt-rtt = "0.4"
embassy-executor = { version = "0.2.0", features = [
    "defmt",
    "nightly",
    "arch-cortex-m",
    "executor-thread",
] }
embassy-futures = { version = "0.1.0", features = ["defmt"] }
embassy-rp = { version = "0.1.0", features = [
    "defmt",
    "nightly",
    "unstable-pac",
    "time-driver",
] }
embassy-time = { version = "0.1.2", features = [
    "defmt",
    "nightly",
    "generic-queue-8",
] }
embassy-usb = { version = "0.1.0", features = ["defmt"] }
panic-probe = { version = "0.3", features = ["print-defmt"] }

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy/", rev = "4d1d125f4157084668a949f9bc24e4417628f9fe" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy/", rev = "4d1d125f4157084668a949f9bc24e4417628f9fe" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy/", rev = "4d1d125f4157084668a949f9bc24e4417628f9fe" }
embassy-time = { git = "https://github.com/embassy-rs/embassy/", rev = "4d1d125f4157084668a949f9bc24e4417628f9fe" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy/", rev = "4d1d125f4157084668a949f9bc24e4417628f9fe" }

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
codegen-units = 1
debug = true
lto = "fat"
